# Generated by Django 3.2.9 on 2022-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('major', models.CharField(max_length=150, null=True)),
                ('hobbies', models.CharField(max_length=300, null=True)),
                ('classes', models.CharField(max_length=150, null=True)),
                ('social_media', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
